///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PadTecTrainingPartI.Modules.TabDataBase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddPersons recording.
    /// </summary>
    [TestModule("7fead2ef-72cc-400c-9ec5-5cd0f9b846ec", ModuleType.Recording, 1)]
    public partial class AddPersons : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PadTecTrainingPartI.Repositories.TabTestDataBaseRepository repository.
        /// </summary>
        public static global::PadTecTrainingPartI.Repositories.TabTestDataBaseRepository repo = global::PadTecTrainingPartI.Repositories.TabTestDataBaseRepository.Instance;

        static AddPersons instance = new AddPersons();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddPersons()
        {
            varFirsName = "";
            varLastName = "";
            varAge = "";
            getCount = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddPersons Instance
        {
            get { return instance; }
        }

#region Variables

        string _varFirsName;

        /// <summary>
        /// Gets or sets the value of variable varFirsName.
        /// </summary>
        [TestVariable("ec81a5ff-a74c-40ea-a5ed-318938790786")]
        public string varFirsName
        {
            get { return _varFirsName; }
            set { _varFirsName = value; }
        }

        string _varLastName;

        /// <summary>
        /// Gets or sets the value of variable varLastName.
        /// </summary>
        [TestVariable("ded649ab-6882-4e3b-b662-fb1877615925")]
        public string varLastName
        {
            get { return _varLastName; }
            set { _varLastName = value; }
        }

        string _varAge;

        /// <summary>
        /// Gets or sets the value of variable varAge.
        /// </summary>
        [TestVariable("e3aeebfe-71f1-4977-8ee0-034e04ba49a5")]
        public string varAge
        {
            get { return _varAge; }
            set { _varAge = value; }
        }

        string _getCount;

        /// <summary>
        /// Gets or sets the value of variable getCount.
        /// </summary>
        [TestVariable("3f447305-c784-4415-b6a7-d9386e67db01")]
        public string getCount
        {
            get { return _getCount; }
            set { _getCount = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varDepartment.
        /// </summary>
        [TestVariable("3d86646c-1aa7-4a7c-a12e-1ebd87be51c4")]
        public string varDepartment
        {
            get { return repo.varDepartment; }
            set { repo.varDepartment = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varGender.
        /// </summary>
        [TestVariable("a1e31cf7-2c5f-4836-b49e-d2cc45a57555")]
        public string varGender
        {
            get { return repo.varGender; }
            set { repo.varGender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varFirsName' on item 'RxMainFrame.RxTabStandard.TxtFirstName'.", repo.RxMainFrame.RxTabStandard.TxtFirstNameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard.TxtFirstName.Element.SetAttributeValue("Text", varFirsName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varLastName' on item 'RxMainFrame.RxTabStandard.TxtLastName'.", repo.RxMainFrame.RxTabStandard.TxtLastNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.TxtLastName.Element.SetAttributeValue("Text", varLastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.CmbDepartment' at 449;14.", repo.RxMainFrame.RxTabStandard.CmbDepartmentInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard.CmbDepartment.Click("449;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'List1000.SelectDepartment'.", repo.List1000.SelectDepartmentInfo, new RecordItemIndex(3));
            repo.List1000.SelectDepartment.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=0,Y=0}.", new RecordItemIndex(4));
            Mouse.MoveTo(0, 0);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varAge' on item 'RxMainFrame.RxTabStandard.UpDownEdit'.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.Element.SetAttributeValue("Text", varAge);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'RxMainFrame.RxTabStandard.Genders.RadioButtonSelected'.", repo.RxMainFrame.RxTabStandard.Genders.RadioButtonSelectedInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabStandard.Genders.RadioButtonSelected.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.BtnAddPerson' at 69;18.", repo.RxMainFrame.RxTabStandard.BtnAddPersonInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabStandard.BtnAddPerson.Click("69;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.RxTabStandard.LblNumberOfPersonsNumber' and assigning its value to variable 'getCount'.", repo.RxMainFrame.RxTabStandard.LblNumberOfPersonsNumberInfo, new RecordItemIndex(8));
            getCount = repo.RxMainFrame.RxTabStandard.LblNumberOfPersonsNumber.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
