///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PadTecTrainingPartI.Modules.TabDataBase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DatabaseResult recording.
    /// </summary>
    [TestModule("15e47028-59a8-4f1a-83bc-580584bcc9d6", ModuleType.Recording, 1)]
    public partial class DatabaseResult : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PadTecTrainingPartI.Repositories.TabTestDataBaseRepository repository.
        /// </summary>
        public static global::PadTecTrainingPartI.Repositories.TabTestDataBaseRepository repo = global::PadTecTrainingPartI.Repositories.TabTestDataBaseRepository.Instance;

        static DatabaseResult instance = new DatabaseResult();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DatabaseResult()
        {
            varValidadeResult = "";
            varFirstName = "";
            varPerson = "";
            varLastName = "";
            varGender = "";
            varAge = "";
            varDepartment = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DatabaseResult Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPerson;

        /// <summary>
        /// Gets or sets the value of variable varPerson.
        /// </summary>
        [TestVariable("768aae94-e62e-450b-ad4f-5dec5c563d6a")]
        public string varPerson
        {
            get { return _varPerson; }
            set { _varPerson = value; }
        }

        string _varLastName;

        /// <summary>
        /// Gets or sets the value of variable varLastName.
        /// </summary>
        [TestVariable("67026185-cee4-4eb4-83e6-cb3cf53b935d")]
        public string varLastName
        {
            get { return _varLastName; }
            set { _varLastName = value; }
        }

        string _varAge;

        /// <summary>
        /// Gets or sets the value of variable varAge.
        /// </summary>
        [TestVariable("aa94b429-d8c6-45ca-b22c-3af4720790d2")]
        public string varAge
        {
            get { return _varAge; }
            set { _varAge = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varFirstName.
        /// </summary>
        [TestVariable("9bced93a-98c7-4f60-8505-d91946b72a9d")]
        public string varFirstName
        {
            get { return repo.varFirstName; }
            set { repo.varFirstName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varValidadeResult.
        /// </summary>
        [TestVariable("860f57ff-2cc9-4330-a5ca-b4b71c971ba4")]
        public string varValidadeResult
        {
            get { return repo.varValidadeResult; }
            set { repo.varValidadeResult = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varGender.
        /// </summary>
        [TestVariable("9082dc15-5007-4292-a2b3-b01e1fc473df")]
        public string varGender
        {
            get { return repo.varGender; }
            set { repo.varGender = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varDepartment.
        /// </summary>
        [TestVariable("e75271ee-4d0f-4ba2-8731-336a248338d3")]
        public string varDepartment
        {
            get { return repo.varDepartment; }
            set { repo.varDepartment = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.RxTabStandard.ListPersons.ListItemContains' and assigning its value to variable 'varPerson'.", repo.RxMainFrame.RxTabStandard.ListPersons.ListItemContainsInfo, new RecordItemIndex(0));
            varPerson = repo.RxMainFrame.RxTabStandard.ListPersons.ListItemContains.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'RxMainFrame.RxTabStandard.ListPersons.ListItemPerson'.", repo.RxMainFrame.RxTabStandard.ListPersons.ListItemPersonInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.ListPersons.ListItemPerson.Select();
            Delay.Milliseconds(0);
            
            Validate_ListItemPerson(repo.RxMainFrame.RxTabStandard.ListPersons.ListItemPersonInfo, varFirstName, varLastName, varGender, varAge, varDepartment);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.BtnDeletePerson' at Center.", repo.RxMainFrame.RxTabStandard.BtnDeletePersonInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard.BtnDeletePerson.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.RxTabStandard.TxtFirstName' and assigning its value to variable 'varPerson'.", repo.RxMainFrame.RxTabStandard.TxtFirstNameInfo, new RecordItemIndex(4));
            //varPerson = repo.RxMainFrame.RxTabStandard.TxtFirstName.Element.GetAttributeValueText("Text");
            //Delay.Milliseconds(0);
            
            //varPerson = retornaNome(repo.RxMainFrame.RxTabStandard.TxtFirstNameInfo, "");
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
