///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PadTecTrainingPartI.Modules.TabDataBase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WriteCountNumber recording.
    /// </summary>
    [TestModule("d96d098a-c0cd-49a8-9807-91355b1d8c64", ModuleType.Recording, 1)]
    public partial class WriteCountNumber : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PadTecTrainingPartI.Repositories.TabIntroductionRepository repository.
        /// </summary>
        public static global::PadTecTrainingPartI.Repositories.TabIntroductionRepository repo = global::PadTecTrainingPartI.Repositories.TabIntroductionRepository.Instance;

        static WriteCountNumber instance = new WriteCountNumber();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WriteCountNumber()
        {
            WriteCount = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WriteCountNumber Instance
        {
            get { return instance; }
        }

#region Variables

        string _WriteCount;

        /// <summary>
        /// Gets or sets the value of variable WriteCount.
        /// </summary>
        [TestVariable("dd87e255-60aa-4b80-9bc4-cfd164316c72")]
        public string WriteCount
        {
            get { return _WriteCount; }
            set { _WriteCount = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Warn, "User", WriteCount, new RecordItemIndex(0));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
