///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PadTecTrainingPartI.Modules.TabUi_Element
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IndentifyUserRow recording.
    /// </summary>
    [TestModule("4a975b1d-31c4-4c6f-8884-794144cd15d1", ModuleType.Recording, 1)]
    public partial class IndentifyUserRow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PadTecTrainingPartI.Repositories.TabUiElementsRepository repository.
        /// </summary>
        public static global::PadTecTrainingPartI.Repositories.TabUiElementsRepository repo = global::PadTecTrainingPartI.Repositories.TabUiElementsRepository.Instance;

        static IndentifyUserRow instance = new IndentifyUserRow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IndentifyUserRow()
        {
            FirstName = "";
            Age = "42";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IndentifyUserRow Instance
        {
            get { return instance; }
        }

#region Variables

        string _FirstName;

        /// <summary>
        /// Gets or sets the value of variable FirstName.
        /// </summary>
        [TestVariable("8a43409a-44ce-403b-92cd-0cd47ddbc429")]
        public string FirstName
        {
            get { return _FirstName; }
            set { _FirstName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Age.
        /// </summary>
        [TestVariable("b7eb0dde-1776-45c7-a7b2-c8fd165314ec")]
        public string Age
        {
            get { return repo.Age; }
            set { repo.Age = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='Table') on item 'RxMainFrame.LabelTable'.", repo.RxMainFrame.LabelTableInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.RxMainFrame.LabelTableInfo, "AccessibleName", "Table");
            Delay.Milliseconds(0);
            
            // VerifyUsers
            Report.Log(ReportLevel.Info, "Section", "VerifyUsers", new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.DataTable.IdentifyFisrtNameValue' and assigning its value to variable 'FirstName'.", repo.RxMainFrame.DataTable.IdentifyFisrtNameValueInfo, new RecordItemIndex(2));
            FirstName = repo.RxMainFrame.DataTable.IdentifyFisrtNameValue.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", FirstName, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'RxMainFrame.DataTable.IdentifyAgeValue'.", repo.RxMainFrame.DataTable.IdentifyAgeValueInfo, new RecordItemIndex(4));
            repo.RxMainFrame.DataTable.IdentifyAgeValue.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Age) on item 'RxMainFrame.DataTable.IdentifyAgeValue'.", repo.RxMainFrame.DataTable.IdentifyAgeValueInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.RxMainFrame.DataTable.IdentifyAgeValueInfo, "Text", Age);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
