///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PadTecTrainingPartI.Modules.TabUi_Element
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectRedLight recording.
    /// </summary>
    [TestModule("d1c0fbec-24a6-495a-85aa-94337ff43edc", ModuleType.Recording, 1)]
    public partial class SelectRedLight : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PadTecTrainingPartI.Repositories.TabUiElementsRepository repository.
        /// </summary>
        public static global::PadTecTrainingPartI.Repositories.TabUiElementsRepository repo = global::PadTecTrainingPartI.Repositories.TabUiElementsRepository.Instance;

        static SelectRedLight instance = new SelectRedLight();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectRedLight()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectRedLight Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'GroupBoxArea.GroupBoxRadioButton.RedLight'.", repo.GroupBoxArea.GroupBoxRadioButton.RedLightInfo, new RecordItemIndex(0));
            repo.GroupBoxArea.GroupBoxRadioButton.RedLight.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'GroupBoxArea.GroupBoxRadioButton.RadioButtonGreenLight'.", repo.GroupBoxArea.GroupBoxRadioButton.RadioButtonGreenLightInfo, new RecordItemIndex(2));
            repo.GroupBoxArea.GroupBoxRadioButton.RadioButtonGreenLight.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(3));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
