///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PadTecTrainingPartI.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DynamicIDsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ee9b2c34-3ee1-49cd-b61d-35277a5aff9c")]
    public partial class DynamicIDsRepository : RepoGenBaseFolder
    {
        static DynamicIDsRepository instance = new DynamicIDsRepository();
        DynamicIDsRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the DynamicIDsRepository element repository.
        /// </summary>
        [RepositoryFolder("ee9b2c34-3ee1-49cd-b61d-35277a5aff9c")]
        public static DynamicIDsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DynamicIDsRepository() 
            : base("DynamicIDsRepository", "/", null, 0, false, "ee9b2c34-3ee1-49cd-b61d-35277a5aff9c", ".\\RepositoryImages\\DynamicIDsRepositoryee9b2c34.rximgres")
        {
            _rxmainframe = new DynamicIDsRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ee9b2c34-3ee1-49cd-b61d-35277a5aff9c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("bb0dbf54-cfcc-4fe5-a33b-0007602c6673")]
        public virtual DynamicIDsRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DynamicIDsRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("bb0dbf54-cfcc-4fe5-a33b-0007602c6673")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chkshowdynamicidInfo;
            RepoItemInfo _pictureboxInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "bb0dbf54-cfcc-4fe5-a33b-0007602c6673", "")
            {
                _chkshowdynamicidInfo = new RepoItemInfo(this, "ChkShowDynamicID", "?/?/tabpage[@controlname='RxTabDynamic']/checkbox[@controlname='chkShowDynamicID']", 30000, null, "5bb61cdc-86f5-4f94-aeec-f6ebc541fd44");
                _pictureboxInfo = new RepoItemInfo(this, "PictureBox", "?/?/tabpage[@controlname='RxTabDynamic']/?/?/picture[@controltypename='PictureBox']", 30000, null, "8f14f2a9-ac96-4de5-9bef-22598673847a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bb0dbf54-cfcc-4fe5-a33b-0007602c6673")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bb0dbf54-cfcc-4fe5-a33b-0007602c6673")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChkShowDynamicID item.
            /// </summary>
            [RepositoryItem("5bb61cdc-86f5-4f94-aeec-f6ebc541fd44")]
            public virtual Ranorex.CheckBox ChkShowDynamicID
            {
                get
                {
                    return _chkshowdynamicidInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowDynamicID item info.
            /// </summary>
            [RepositoryItemInfo("5bb61cdc-86f5-4f94-aeec-f6ebc541fd44")]
            public virtual RepoItemInfo ChkShowDynamicIDInfo
            {
                get
                {
                    return _chkshowdynamicidInfo;
                }
            }

            /// <summary>
            /// The PictureBox item.
            /// </summary>
            [RepositoryItem("8f14f2a9-ac96-4de5-9bef-22598673847a")]
            public virtual Ranorex.Picture PictureBox
            {
                get
                {
                    return _pictureboxInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureBox item info.
            /// </summary>
            [RepositoryItemInfo("8f14f2a9-ac96-4de5-9bef-22598673847a")]
            public virtual RepoItemInfo PictureBoxInfo
            {
                get
                {
                    return _pictureboxInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
