///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PadTecTrainingPartI.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SelectTabRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("43d743c3-ce4c-4cbc-a29f-5479a815e3ea")]
    public partial class SelectTabRepository : RepoGenBaseFolder
    {
        static SelectTabRepository instance = new SelectTabRepository();
        SelectTabRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the SelectTabRepository element repository.
        /// </summary>
        [RepositoryFolder("43d743c3-ce4c-4cbc-a29f-5479a815e3ea")]
        public static SelectTabRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SelectTabRepository() 
            : base("SelectTabRepository", "/", null, 0, false, "43d743c3-ce4c-4cbc-a29f-5479a815e3ea", ".\\RepositoryImages\\SelectTabRepository43d743c3.rximgres")
        {
            _rxmainframe = new SelectTabRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

        string _varTab = "Introduction";

        /// <summary>
        /// Gets or sets the value of variable varTab.
        /// </summary>
        [TestVariable("2ee607b2-0e27-4ef4-8b1f-a9da562f3b92")]
        public string varTab
        {
            get { return _varTab; }
            set { _varTab = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("43d743c3-ce4c-4cbc-a29f-5479a815e3ea")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("ae783918-b0d9-4585-936e-d724edc85de8")]
        public virtual SelectTabRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SelectTabRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("ae783918-b0d9-4585-936e-d724edc85de8")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabpageInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "ae783918-b0d9-4585-936e-d724edc85de8", "")
            {
                _tabpageInfo = new RepoItemInfo(this, "TabPage", "tabpagelist[@controlname='RxTabcontrol']/?/?/tabpage[@accessiblename=$varTab]", 30000, null, "d9ebd652-d756-484d-b642-820cf4eda552");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ae783918-b0d9-4585-936e-d724edc85de8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ae783918-b0d9-4585-936e-d724edc85de8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TabPage item.
            /// </summary>
            [RepositoryItem("d9ebd652-d756-484d-b642-820cf4eda552")]
            public virtual Ranorex.TabPage TabPage
            {
                get
                {
                    return _tabpageInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabPage item info.
            /// </summary>
            [RepositoryItemInfo("d9ebd652-d756-484d-b642-820cf4eda552")]
            public virtual RepoItemInfo TabPageInfo
            {
                get
                {
                    return _tabpageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
