///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PadTecTrainingPartI.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TabImageBasedAutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3ae96d15-0947-4e22-901a-a562af545409")]
    public partial class TabImageBasedAutomationRepository : RepoGenBaseFolder
    {
        static TabImageBasedAutomationRepository instance = new TabImageBasedAutomationRepository();
        TabImageBasedAutomationRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the TabImageBasedAutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("3ae96d15-0947-4e22-901a-a562af545409")]
        public static TabImageBasedAutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TabImageBasedAutomationRepository() 
            : base("TabImageBasedAutomationRepository", "/", null, 0, false, "3ae96d15-0947-4e22-901a-a562af545409", ".\\RepositoryImages\\TabImageBasedAutomationRepository3ae96d15.rximgres")
        {
            _rxmainframe = new TabImageBasedAutomationRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

        string _varTab = "Image-based automation";

        /// <summary>
        /// Gets or sets the value of variable varTab.
        /// </summary>
        [TestVariable("29eda873-150d-46d4-841f-81676efb03d0")]
        public string varTab
        {
            get { return _varTab; }
            set { _varTab = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3ae96d15-0947-4e22-901a-a562af545409")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("e1b3d31d-b86e-4391-adda-303ea1a080f5")]
        public virtual TabImageBasedAutomationRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TabImageBasedAutomationRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("e1b3d31d-b86e-4391-adda-303ea1a080f5")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabpageInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "e1b3d31d-b86e-4391-adda-303ea1a080f5", "")
            {
                _tabpageInfo = new RepoItemInfo(this, "TabPage", "tabpagelist[@controlname='RxTabcontrol']/?/?/tabpage[@accessiblename=$varTab]", 30000, null, "0569e7da-8f43-4509-82b2-d0729017dda4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e1b3d31d-b86e-4391-adda-303ea1a080f5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e1b3d31d-b86e-4391-adda-303ea1a080f5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TabPage item.
            /// </summary>
            [RepositoryItem("0569e7da-8f43-4509-82b2-d0729017dda4")]
            public virtual Ranorex.TabPage TabPage
            {
                get
                {
                    return _tabpageInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabPage item info.
            /// </summary>
            [RepositoryItemInfo("0569e7da-8f43-4509-82b2-d0729017dda4")]
            public virtual RepoItemInfo TabPageInfo
            {
                get
                {
                    return _tabpageInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
