///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PadTecTrainingPartI.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TabIntroductionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("82029641-968e-469d-9a20-d3e878f2c53d")]
    public partial class TabIntroductionRepository : RepoGenBaseFolder
    {
        static TabIntroductionRepository instance = new TabIntroductionRepository();
        TabIntroductionRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the TabIntroductionRepository element repository.
        /// </summary>
        [RepositoryFolder("82029641-968e-469d-9a20-d3e878f2c53d")]
        public static TabIntroductionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TabIntroductionRepository() 
            : base("TabIntroductionRepository", "/", null, 0, false, "82029641-968e-469d-9a20-d3e878f2c53d", ".\\RepositoryImages\\TabIntroductionRepository82029641.rximgres")
        {
            _rxmainframe = new TabIntroductionRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

        string _varTab = "Introduction";

        /// <summary>
        /// Gets or sets the value of variable varTab.
        /// </summary>
        [TestVariable("c225190b-be06-4caf-9659-9e8ca3f9defd")]
        public string varTab
        {
            get { return _varTab; }
            set { _varTab = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("82029641-968e-469d-9a20-d3e878f2c53d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("3520b261-485b-4d59-b8e2-166da6c551fa")]
        public virtual TabIntroductionRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TabIntroductionRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("3520b261-485b-4d59-b8e2-166da6c551fa")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            TabIntroductionRepositoryFolders.RxTabStandardFolder _rxtabstandard;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "3520b261-485b-4d59-b8e2-166da6c551fa", "")
            {
                _rxtabstandard = new TabIntroductionRepositoryFolders.RxTabStandardFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3520b261-485b-4d59-b8e2-166da6c551fa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3520b261-485b-4d59-b8e2-166da6c551fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("ddf0f889-7a17-49eb-bf82-814940e77a5a")]
            public virtual TabIntroductionRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("ddf0f889-7a17-49eb-bf82-814940e77a5a")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "ddf0f889-7a17-49eb-bf82-814940e77a5a", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ddf0f889-7a17-49eb-bf82-814940e77a5a")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ddf0f889-7a17-49eb-bf82-814940e77a5a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
