///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PadTecTrainingPartI.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TabTestDataBaseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2b197088-c74f-438c-863e-bb2f15e29f82")]
    public partial class TabTestDataBaseRepository : RepoGenBaseFolder
    {
        static TabTestDataBaseRepository instance = new TabTestDataBaseRepository();
        TabTestDataBaseRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        TabTestDataBaseRepositoryFolders.List1000AppFolder _list1000;

        /// <summary>
        /// Gets the singleton class instance representing the TabTestDataBaseRepository element repository.
        /// </summary>
        [RepositoryFolder("2b197088-c74f-438c-863e-bb2f15e29f82")]
        public static TabTestDataBaseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TabTestDataBaseRepository() 
            : base("TabTestDataBaseRepository", "/", null, 0, false, "2b197088-c74f-438c-863e-bb2f15e29f82", ".\\RepositoryImages\\TabTestDataBaseRepository2b197088.rximgres")
        {
            _rxmainframe = new TabTestDataBaseRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new TabTestDataBaseRepositoryFolders.List1000AppFolder(this);
        }

#region Variables

        string _varTab = "Test database";

        /// <summary>
        /// Gets or sets the value of variable varTab.
        /// </summary>
        [TestVariable("cc3d7c73-394a-4a34-86f5-5bbc75bbb08c")]
        public string varTab
        {
            get { return _varTab; }
            set { _varTab = value; }
        }

        string _varGender = "";

        /// <summary>
        /// Gets or sets the value of variable varGender.
        /// </summary>
        [TestVariable("a1e31cf7-2c5f-4836-b49e-d2cc45a57555")]
        public string varGender
        {
            get { return _varGender; }
            set { _varGender = value; }
        }

        string _varDepartment = "";

        /// <summary>
        /// Gets or sets the value of variable varDepartment.
        /// </summary>
        [TestVariable("3d86646c-1aa7-4a7c-a12e-1ebd87be51c4")]
        public string varDepartment
        {
            get { return _varDepartment; }
            set { _varDepartment = value; }
        }

        string _varValidadeResult = "";

        /// <summary>
        /// Gets or sets the value of variable varValidadeResult.
        /// </summary>
        [TestVariable("860f57ff-2cc9-4330-a5ca-b4b71c971ba4")]
        public string varValidadeResult
        {
            get { return _varValidadeResult; }
            set { _varValidadeResult = value; }
        }

        string _varFirstName = "";

        /// <summary>
        /// Gets or sets the value of variable varFirstName.
        /// </summary>
        [TestVariable("9bced93a-98c7-4f60-8505-d91946b72a9d")]
        public string varFirstName
        {
            get { return _varFirstName; }
            set { _varFirstName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2b197088-c74f-438c-863e-bb2f15e29f82")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("00d0004b-fcbd-4274-849a-e43623690f21")]
        public virtual TabTestDataBaseRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("701abb23-19d9-4dd6-bf2f-049c5b474106")]
        public virtual TabTestDataBaseRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TabTestDataBaseRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("00d0004b-fcbd-4274-849a-e43623690f21")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            TabTestDataBaseRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _tabpageInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "00d0004b-fcbd-4274-849a-e43623690f21", "")
            {
                _rxtabstandard = new TabTestDataBaseRepositoryFolders.RxTabStandardFolder(this);
                _tabpageInfo = new RepoItemInfo(this, "TabPage", "tabpagelist[@controlname='RxTabcontrol']/?/?/tabpage[@accessiblename=$varTab]", 30000, null, "65f198ad-c00f-4abf-9c10-ec252b80fae7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("00d0004b-fcbd-4274-849a-e43623690f21")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("00d0004b-fcbd-4274-849a-e43623690f21")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TabPage item.
            /// </summary>
            [RepositoryItem("65f198ad-c00f-4abf-9c10-ec252b80fae7")]
            public virtual Ranorex.TabPage TabPage
            {
                get
                {
                    return _tabpageInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabPage item info.
            /// </summary>
            [RepositoryItemInfo("65f198ad-c00f-4abf-9c10-ec252b80fae7")]
            public virtual RepoItemInfo TabPageInfo
            {
                get
                {
                    return _tabpageInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("1ecc3719-6836-4fd2-b64e-92f6332cb6d7")]
            public virtual TabTestDataBaseRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("1ecc3719-6836-4fd2-b64e-92f6332cb6d7")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            TabTestDataBaseRepositoryFolders.GendersFolder _genders;
            TabTestDataBaseRepositoryFolders.ListPersonsFolder _listpersons;
            RepoItemInfo _txtfirstnameInfo;
            RepoItemInfo _txtlastnameInfo;
            RepoItemInfo _cmbdepartmentInfo;
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;
            RepoItemInfo _btndeletepersonInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "1ecc3719-6836-4fd2-b64e-92f6332cb6d7", "")
            {
                _genders = new TabTestDataBaseRepositoryFolders.GendersFolder(this);
                _listpersons = new TabTestDataBaseRepositoryFolders.ListPersonsFolder(this);
                _txtfirstnameInfo = new RepoItemInfo(this, "TxtFirstName", "text[@controlname='txtFirstName']", 30000, null, "8655294a-282a-4c68-82f0-287f332c7339");
                _txtlastnameInfo = new RepoItemInfo(this, "TxtLastName", "text[@controlname='txtLastName']", 30000, null, "a7d93d1c-922b-4eb2-a8c5-f8a15e2bb287");
                _cmbdepartmentInfo = new RepoItemInfo(this, "CmbDepartment", "combobox[@controlname='cmbDepartment']", 30000, null, "0a0e59e0-a5aa-444c-8b9c-9f760aa16d2e");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", "?/?/text[@controlname='upDownEdit']", 30000, null, "7fd7afc6-a542-47a8-8347-640d1a917e77");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", 30000, null, "70ba2f6d-b420-4cca-827f-92c48ff84fc8");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "6a6f13be-0ddc-4ed8-9908-f38934c06f4e");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "button[@controlname='btnDeletePerson']", 30000, null, "3c54afd8-bddd-4a32-827b-0c0ef80d9fa5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1ecc3719-6836-4fd2-b64e-92f6332cb6d7")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ecc3719-6836-4fd2-b64e-92f6332cb6d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtFirstName item.
            /// </summary>
            [RepositoryItem("8655294a-282a-4c68-82f0-287f332c7339")]
            public virtual Ranorex.Text TxtFirstName
            {
                get
                {
                    return _txtfirstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtFirstName item info.
            /// </summary>
            [RepositoryItemInfo("8655294a-282a-4c68-82f0-287f332c7339")]
            public virtual RepoItemInfo TxtFirstNameInfo
            {
                get
                {
                    return _txtfirstnameInfo;
                }
            }

            /// <summary>
            /// The TxtLastName item.
            /// </summary>
            [RepositoryItem("a7d93d1c-922b-4eb2-a8c5-f8a15e2bb287")]
            public virtual Ranorex.Text TxtLastName
            {
                get
                {
                    return _txtlastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtLastName item info.
            /// </summary>
            [RepositoryItemInfo("a7d93d1c-922b-4eb2-a8c5-f8a15e2bb287")]
            public virtual RepoItemInfo TxtLastNameInfo
            {
                get
                {
                    return _txtlastnameInfo;
                }
            }

            /// <summary>
            /// The CmbDepartment item.
            /// </summary>
            [RepositoryItem("0a0e59e0-a5aa-444c-8b9c-9f760aa16d2e")]
            public virtual Ranorex.ComboBox CmbDepartment
            {
                get
                {
                    return _cmbdepartmentInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbDepartment item info.
            /// </summary>
            [RepositoryItemInfo("0a0e59e0-a5aa-444c-8b9c-9f760aa16d2e")]
            public virtual RepoItemInfo CmbDepartmentInfo
            {
                get
                {
                    return _cmbdepartmentInfo;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("7fd7afc6-a542-47a8-8347-640d1a917e77")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("7fd7afc6-a542-47a8-8347-640d1a917e77")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("70ba2f6d-b420-4cca-827f-92c48ff84fc8")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("70ba2f6d-b420-4cca-827f-92c48ff84fc8")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("6a6f13be-0ddc-4ed8-9908-f38934c06f4e")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("6a6f13be-0ddc-4ed8-9908-f38934c06f4e")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("3c54afd8-bddd-4a32-827b-0c0ef80d9fa5")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("3c54afd8-bddd-4a32-827b-0c0ef80d9fa5")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The Genders folder.
            /// </summary>
            [RepositoryFolder("bd4ddfbd-889e-4590-8841-95eac2227150")]
            public virtual TabTestDataBaseRepositoryFolders.GendersFolder Genders
            {
                get { return _genders; }
            }

            /// <summary>
            /// The ListPersons folder.
            /// </summary>
            [RepositoryFolder("ac038457-d853-48fc-acb0-a586bca9cf68")]
            public virtual TabTestDataBaseRepositoryFolders.ListPersonsFolder ListPersons
            {
                get { return _listpersons; }
            }
        }

        /// <summary>
        /// The GendersFolder folder.
        /// </summary>
        [RepositoryFolder("bd4ddfbd-889e-4590-8841-95eac2227150")]
        public partial class GendersFolder : RepoGenBaseFolder
        {
            RepoItemInfo _radiobuttonselectedInfo;

            /// <summary>
            /// Creates a new Genders  folder.
            /// </summary>
            public GendersFolder(RepoGenBaseFolder parentFolder) :
                    base("Genders", "container[@controlname='grpGender']/?/?", parentFolder, 30000, null, false, "bd4ddfbd-889e-4590-8841-95eac2227150", "")
            {
                _radiobuttonselectedInfo = new RepoItemInfo(this, "RadioButtonSelected", "radiobutton[@accessiblename=$varGender]", 30000, null, "2042947c-86da-41be-9c65-a7883210bb25");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bd4ddfbd-889e-4590-8841-95eac2227150")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bd4ddfbd-889e-4590-8841-95eac2227150")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RadioButtonSelected item.
            /// </summary>
            [RepositoryItem("2042947c-86da-41be-9c65-a7883210bb25")]
            public virtual Ranorex.RadioButton RadioButtonSelected
            {
                get
                {
                    return _radiobuttonselectedInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonSelected item info.
            /// </summary>
            [RepositoryItemInfo("2042947c-86da-41be-9c65-a7883210bb25")]
            public virtual RepoItemInfo RadioButtonSelectedInfo
            {
                get
                {
                    return _radiobuttonselectedInfo;
                }
            }
        }

        /// <summary>
        /// The ListPersonsFolder folder.
        /// </summary>
        [RepositoryFolder("ac038457-d853-48fc-acb0-a586bca9cf68")]
        public partial class ListPersonsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _listitempersonInfo;
            RepoItemInfo _listitemcontainsInfo;

            /// <summary>
            /// Creates a new ListPersons  folder.
            /// </summary>
            public ListPersonsFolder(RepoGenBaseFolder parentFolder) :
                    base("ListPersons", "list[@controlname='lstPersonList']/?/?", parentFolder, 30000, null, false, "ac038457-d853-48fc-acb0-a586bca9cf68", "")
            {
                _listitempersonInfo = new RepoItemInfo(this, "ListItemPerson", "listitem[@accessiblename=$varValidadeResult]", 30000, null, "46d0c52c-1a2b-478f-8fb8-6371ff007ee6");
                _listitemcontainsInfo = new RepoItemInfo(this, "ListItemContains", "listitem[@accessiblename>$varFirstName]", 30000, null, "36bbf02d-508d-40e3-aeee-d1acc26e1d83");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ac038457-d853-48fc-acb0-a586bca9cf68")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ac038457-d853-48fc-acb0-a586bca9cf68")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItemPerson item.
            /// </summary>
            [RepositoryItem("46d0c52c-1a2b-478f-8fb8-6371ff007ee6")]
            public virtual Ranorex.ListItem ListItemPerson
            {
                get
                {
                    return _listitempersonInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPerson item info.
            /// </summary>
            [RepositoryItemInfo("46d0c52c-1a2b-478f-8fb8-6371ff007ee6")]
            public virtual RepoItemInfo ListItemPersonInfo
            {
                get
                {
                    return _listitempersonInfo;
                }
            }

            /// <summary>
            /// The ListItemContains item.
            /// </summary>
            [RepositoryItem("36bbf02d-508d-40e3-aeee-d1acc26e1d83")]
            public virtual Ranorex.ListItem ListItemContains
            {
                get
                {
                    return _listitemcontainsInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemContains item info.
            /// </summary>
            [RepositoryItemInfo("36bbf02d-508d-40e3-aeee-d1acc26e1d83")]
            public virtual RepoItemInfo ListItemContainsInfo
            {
                get
                {
                    return _listitemcontainsInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("701abb23-19d9-4dd6-bf2f-049c5b474106")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selectdepartmentInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "701abb23-19d9-4dd6-bf2f-049c5b474106", "")
            {
                _selectdepartmentInfo = new RepoItemInfo(this, "SelectDepartment", "listitem[@text=$varDepartment]", 30000, null, "3c92d433-45f4-4131-a168-ef223cda787e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("701abb23-19d9-4dd6-bf2f-049c5b474106")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("701abb23-19d9-4dd6-bf2f-049c5b474106")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectDepartment item.
            /// </summary>
            [RepositoryItem("3c92d433-45f4-4131-a168-ef223cda787e")]
            public virtual Ranorex.ListItem SelectDepartment
            {
                get
                {
                    return _selectdepartmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SelectDepartment item info.
            /// </summary>
            [RepositoryItemInfo("3c92d433-45f4-4131-a168-ef223cda787e")]
            public virtual RepoItemInfo SelectDepartmentInfo
            {
                get
                {
                    return _selectdepartmentInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
