///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PadTecTrainingPartI.Repositories
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TabUiElementsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f63e9464-0aa4-4e17-ad72-98dddd6dd876")]
    public partial class TabUiElementsRepository : RepoGenBaseFolder
    {
        static TabUiElementsRepository instance = new TabUiElementsRepository();
        TabUiElementsRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        TabUiElementsRepositoryFolders.GroupBoxAreaFolder _groupboxarea;

        /// <summary>
        /// Gets the singleton class instance representing the TabUiElementsRepository element repository.
        /// </summary>
        [RepositoryFolder("f63e9464-0aa4-4e17-ad72-98dddd6dd876")]
        public static TabUiElementsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TabUiElementsRepository() 
            : base("TabUiElementsRepository", "/", null, 0, false, "f63e9464-0aa4-4e17-ad72-98dddd6dd876", ".\\RepositoryImages\\TabUiElementsRepositoryf63e9464.rximgres")
        {
            _rxmainframe = new TabUiElementsRepositoryFolders.RxMainFrameAppFolder(this);
            _groupboxarea = new TabUiElementsRepositoryFolders.GroupBoxAreaFolder(this);
        }

#region Variables

        string _Age = "42";

        /// <summary>
        /// Gets or sets the value of variable Age.
        /// </summary>
        [TestVariable("b7eb0dde-1776-45c7-a7b2-c8fd165314ec")]
        public string Age
        {
            get { return _Age; }
            set { _Age = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f63e9464-0aa4-4e17-ad72-98dddd6dd876")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("46af0e92-da4e-45c1-91ef-79728195b9b2")]
        public virtual TabUiElementsRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The GroupBoxArea folder.
        /// </summary>
        [RepositoryFolder("20338f10-32dc-4a45-b1a2-c4c8d291c9fc")]
        public virtual TabUiElementsRepositoryFolders.GroupBoxAreaFolder GroupBoxArea
        {
            get { return _groupboxarea; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TabUiElementsRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("46af0e92-da4e-45c1-91ef-79728195b9b2")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            TabUiElementsRepositoryFolders.DataTableFolder _datatable;
            RepoItemInfo _labeltableInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "46af0e92-da4e-45c1-91ef-79728195b9b2", "")
            {
                _datatable = new TabUiElementsRepositoryFolders.DataTableFolder(this);
                _labeltableInfo = new RepoItemInfo(this, "LabelTable", "?/?/tabpage[@controlname='RxTabUIElements']/?/text[@accessiblename='Table']", 30000, null, "0d84e17b-cf51-44e2-a3c1-fff7ee284032");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("46af0e92-da4e-45c1-91ef-79728195b9b2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("46af0e92-da4e-45c1-91ef-79728195b9b2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LabelTable item.
            /// </summary>
            [RepositoryItem("0d84e17b-cf51-44e2-a3c1-fff7ee284032")]
            public virtual Ranorex.Text LabelTable
            {
                get
                {
                    return _labeltableInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelTable item info.
            /// </summary>
            [RepositoryItemInfo("0d84e17b-cf51-44e2-a3c1-fff7ee284032")]
            public virtual RepoItemInfo LabelTableInfo
            {
                get
                {
                    return _labeltableInfo;
                }
            }

            /// <summary>
            /// The DataTable folder.
            /// </summary>
            [RepositoryFolder("6ef26679-1fbb-4003-aa99-f2a3c55d1b29")]
            public virtual TabUiElementsRepositoryFolders.DataTableFolder DataTable
            {
                get { return _datatable; }
            }
        }

        /// <summary>
        /// The DataTableFolder folder.
        /// </summary>
        [RepositoryFolder("6ef26679-1fbb-4003-aa99-f2a3c55d1b29")]
        public partial class DataTableFolder : RepoGenBaseFolder
        {
            RepoItemInfo _identifyfisrtnamevalueInfo;
            RepoItemInfo _identifyagevalueInfo;

            /// <summary>
            /// Creates a new DataTable  folder.
            /// </summary>
            public DataTableFolder(RepoGenBaseFolder parentFolder) :
                    base("DataTable", "?/?/tabpage[@controlname='RxTabUIElements']/table[@controlname='dataGridView1']", parentFolder, 30000, null, false, "6ef26679-1fbb-4003-aa99-f2a3c55d1b29", "")
            {
                _identifyfisrtnamevalueInfo = new RepoItemInfo(this, "IdentifyFisrtNameValue", ".//cell[@text='Thomas' and @accessiblename>'FirstName']", 30000, null, "2e5fa68d-be46-4e3a-bbb2-2ae11aa0f61f");
                _identifyagevalueInfo = new RepoItemInfo(this, "IdentifyAgeValue", ".//cell[@text=$Age and @accessiblename>'Age']", 30000, null, "a5894810-a9ee-4c87-b231-c61f7b3b38ef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6ef26679-1fbb-4003-aa99-f2a3c55d1b29")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6ef26679-1fbb-4003-aa99-f2a3c55d1b29")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IdentifyFisrtNameValue item.
            /// </summary>
            [RepositoryItem("2e5fa68d-be46-4e3a-bbb2-2ae11aa0f61f")]
            public virtual Ranorex.Cell IdentifyFisrtNameValue
            {
                get
                {
                    return _identifyfisrtnamevalueInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The IdentifyFisrtNameValue item info.
            /// </summary>
            [RepositoryItemInfo("2e5fa68d-be46-4e3a-bbb2-2ae11aa0f61f")]
            public virtual RepoItemInfo IdentifyFisrtNameValueInfo
            {
                get
                {
                    return _identifyfisrtnamevalueInfo;
                }
            }

            /// <summary>
            /// The IdentifyAgeValue item.
            /// </summary>
            [RepositoryItem("a5894810-a9ee-4c87-b231-c61f7b3b38ef")]
            public virtual Ranorex.Cell IdentifyAgeValue
            {
                get
                {
                    return _identifyagevalueInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The IdentifyAgeValue item info.
            /// </summary>
            [RepositoryItemInfo("a5894810-a9ee-4c87-b231-c61f7b3b38ef")]
            public virtual RepoItemInfo IdentifyAgeValueInfo
            {
                get
                {
                    return _identifyagevalueInfo;
                }
            }
        }

        /// <summary>
        /// The GroupBoxAreaFolder folder.
        /// </summary>
        [RepositoryFolder("20338f10-32dc-4a45-b1a2-c4c8d291c9fc")]
        public partial class GroupBoxAreaFolder : RepoGenBaseFolder
        {
            TabUiElementsRepositoryFolders.GroupBoxRadioButtonFolder _groupboxradiobutton;

            /// <summary>
            /// Creates a new GroupBoxArea  folder.
            /// </summary>
            public GroupBoxAreaFolder(RepoGenBaseFolder parentFolder) :
                    base("GroupBoxArea", "", parentFolder, 0, null, false, "20338f10-32dc-4a45-b1a2-c4c8d291c9fc", "")
            {
                _groupboxradiobutton = new TabUiElementsRepositoryFolders.GroupBoxRadioButtonFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("20338f10-32dc-4a45-b1a2-c4c8d291c9fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GroupBoxRadioButton folder.
            /// </summary>
            [RepositoryFolder("de117b06-053f-4268-b7d3-d1181f5fca37")]
            public virtual TabUiElementsRepositoryFolders.GroupBoxRadioButtonFolder GroupBoxRadioButton
            {
                get { return _groupboxradiobutton; }
            }
        }

        /// <summary>
        /// The GroupBoxRadioButtonFolder folder.
        /// </summary>
        [RepositoryFolder("de117b06-053f-4268-b7d3-d1181f5fca37")]
        public partial class GroupBoxRadioButtonFolder : RepoGenBaseFolder
        {
            RepoItemInfo _redlightInfo;
            RepoItemInfo _radiobuttongreenlightInfo;

            /// <summary>
            /// Creates a new GroupBoxRadioButton  folder.
            /// </summary>
            public GroupBoxRadioButtonFolder(RepoGenBaseFolder parentFolder) :
                    base("GroupBoxRadioButton", "/form[@controlname='RxMainFrame']/tabpagelist/tabpage/container[@controlname='grpBox']/container[@controlname='grpBoxRadioButton']/?/?", parentFolder, 30000, null, false, "de117b06-053f-4268-b7d3-d1181f5fca37", "")
            {
                _redlightInfo = new RepoItemInfo(this, "RedLight", "radiobutton[@text='Red light']", 30000, null, "2dbbc9e0-1da5-4f25-9e99-663ead32372b");
                _radiobuttongreenlightInfo = new RepoItemInfo(this, "RadioButtonGreenLight", "radiobutton[@text='Green light']", 30000, null, "7d0d91dd-0f5e-42d8-9be4-fc8cd1ed706d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("de117b06-053f-4268-b7d3-d1181f5fca37")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("de117b06-053f-4268-b7d3-d1181f5fca37")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RedLight item.
            /// </summary>
            [RepositoryItem("2dbbc9e0-1da5-4f25-9e99-663ead32372b")]
            public virtual Ranorex.RadioButton RedLight
            {
                get
                {
                    return _redlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RedLight item info.
            /// </summary>
            [RepositoryItemInfo("2dbbc9e0-1da5-4f25-9e99-663ead32372b")]
            public virtual RepoItemInfo RedLightInfo
            {
                get
                {
                    return _redlightInfo;
                }
            }

            /// <summary>
            /// The RadioButtonGreenLight item.
            /// </summary>
            [RepositoryItem("7d0d91dd-0f5e-42d8-9be4-fc8cd1ed706d")]
            public virtual Ranorex.RadioButton RadioButtonGreenLight
            {
                get
                {
                    return _radiobuttongreenlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonGreenLight item info.
            /// </summary>
            [RepositoryItemInfo("7d0d91dd-0f5e-42d8-9be4-fc8cd1ed706d")]
            public virtual RepoItemInfo RadioButtonGreenLightInfo
            {
                get
                {
                    return _radiobuttongreenlightInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
